FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 curl wget openssh-client -y
RUN mkdir app
WORKDIR /app

RUN python3 -m pip install --upgrade pip
RUN pip3 install \
    opencv-python==3.4.10.37 \
    optuna==2.0.0 \
    pandas==1.1.5 \
    matplotlib==3.3.4 \
    torch==1.5.0 \
    numpy==1.17.4 \
    Pillow==7.0.0 \
    bs4 \
    scikit-learn==0.24.2 \
    torchvision==0.6.0 \
    pytorchtools \
    joblib\
    scikit-image==0.15.0 \
    pathlib \
    seaborn \
    scikit-plot==0.3.7 \
    torch-summary

